module

public import Noperthedron.RationalApprox.TrigLemmas
public import Noperthedron.Vertices.Taylor
public import Mathlib.Analysis.Real.Pi.Bounds

@[expose] public section

/-!
# Exact and rational vertices of Nopert #231

Nopert #231 (candidate R1) is a small repair of Nopert #214 with fivefold
symmetry about z, parallel pentagonal caps and exactly planar quadrilaterals
(nopert229/notes/R.md). Its twenty vertices rotate four seed vertices about
the z axis in steps of 2π/5. `rationalVertices` is the certified rational
model (2^52 denominators, quads exactly planar in ℚ), generated by
`nopert229/codebdd231.cc` and copied here by `scripts/nopert231_update_vertices.py`.
`exactVertex` rotates the rational seeds exactly. `C5Model` (below) is any
fivefold-symmetric polyhedron within `modelErrorQ` of the rational model, and
the certificates cover all of them (see `Ideal231` for the exactly planar one).
Vertices are scaled to lie inside the unit sphere (the GoodPoly invariant).
-/

namespace Noperthedron.Nopert231

abbrev VertexIndex := Fin 20
abbrev SeedIndex := Fin 4
abbrev OrbitIndex := Fin 5

def rationalVertices : VertexIndex → Fin 3 → ℚ := ![
  ![95607336653427/2251799813685248, 2553994589029803/4503599627370496, 2543749016773927/4503599627370496],
  ![-208438279230124513419938539900593729786333151670672382452695213771090003193121/1224076267873291663352087115250153476427671495980998537313412680646657006632960, 57448722305781971304474826913106443457274909479993890866304180896460827989341/61203813393664583167604355762507673821383574799049926865670634032332850331648, 367115662294595894988744286384259356731936051817244634113235267091647325950663/1224076267873291663352087115250153476427671495980998537313412680646657006632960],
  ![-1259122882292673/4503599627370496, 1003756700517363/1125899906842624, -189740010677929/4503599627370496],
  ![129357367826243/2251799813685248, 1354183983942773/2251799813685248, -1718020733186383/2251799813685248],
  ![-1184952306426843/2251799813685248, 971083692611601/4503599627370496, 2543749016773927/4503599627370496],
  ![-57857530229763606426497640469552665709380521964377024366132248488452642582469/61203813393664550312670551475851327496735528613702670442743259483129222529024, 156816046245116132341427751865467696780831261405029140677663773475231993149043/1224076267873291006253411029517026549934710572274053408854865189662584450580480, 367115662294595738657192239123829929846439883205010566870504585387083689177151/1224076267873291006253411029517026549934710572274053408854865189662584450580480],
  ![-2103803885921323/2251799813685248, 43214492689577/4503599627370496, -189740010677929/4503599627370496],
  ![-2495863754370771/4503599627370496, 1082984064301251/4503599627370496, -1718020733186383/2251799813685248],
  ![-206987034268199/562949953421312, -976915930537539/2251799813685248, 2543749016773927/4503599627370496],
  ![-63340015564030527198107852278176784164146786548426340968395891092954251299121/153009533484161347847340811762914123864110402605926904161630182756236100894720, -6575354997217383081888318945435022807101187628276764043217871548421017359161/7650476674208067392367040588145706193205520130296345208081509137811805044736, 45889457786824457174989827645152236525755154450661293996259063698907409780873/153009533484161347847340811762914123864110402605926904161630182756236100894720],
  ![-167665216504287/562949953421312, -3988318776780709/4503599627370496, -189740010677929/4503599627370496],
  ![-900621683571271/2251799813685248, -2039047006872871/4503599627370496, -1718020733186383/2251799813685248],
  ![336626108396849/1125899906842624, -2178618191058463/4503599627370496, 2543749016773927/4503599627370496],
  ![421990172431563256256770853494300200914179038394414607422533541700630586600981/612038133936645565896011849626872562480963051653843574360286431972794205995008, -201755726616351692488330147129522620952630328951113019563865392193677629636355/306019066968322782948005924813436281240481525826921787180143215986397102997504, 91778915573648940260039741801482534617613791631561978566790514301857321430975/306019066968322782948005924813436281240481525826921787180143215986397102997504],
  ![3378625351596573/4503599627370496, -2508131054709461/4503599627370496, -189740010677929/4503599627370496],
  ![1382634131466375/4503599627370496, -1171592209603713/2251799813685248, -1718020733186383/2251799813685248],
  ![2488081780105029/4503599627370496, 75921471311517/562949953421312, 2543749016773927/4503599627370496],
  ![1028328663474514024973778438544524683236032711287114790461837659695584982995665/1224076267873290930929995525476721137618266804205983718947653915018875920973824, 553289213659432993646591174031615708127438898645659856490992412775595339971335/1224076267873290930929995525476721137618266804205983718947653915018875920973824, 367115662294595734608597090007765800576198992021910177528375065891547393476625/1224076267873290930929995525476721137618266804205983718947653915018875920973824],
  ![1714713517286521/2251799813685248, 609552134182785/1125899906842624, -189740010677929/4503599627370496],
  ![2655758254394453/4503599627370496, 147719848473375/1125899906842624, -1718020733186383/2251799813685248]
]

/-! ### Fast evaluation in compiled code

`rationalVertices` is a `![…]` literal of big rationals. In compiled code each
access walks the `Fin.cons` chain and re-normalizes the rational literal (a
GMP gcd on ~260-bit numbers for the planarized vertices), and the native
certificate checkers access vertices tens of thousands of times per row. The
`@[csimp]` lemma below makes compiled code read a table of rationals computed
once at initialization instead. It is a proved equality, so it changes speed
only, not what is checked. (The table must hold data, not functions: the
compiler eta-expands function-valued definitions, so a table of closures
would still recompute on every access.) -/

/-- The coordinates of `rationalVertices`, computed once. -/
def rationalVerticesTable : Array (Array ℚ) :=
  Array.ofFn fun i : VertexIndex => Array.ofFn fun c : Fin 3 => rationalVertices i c

def rationalVerticesImpl (i : VertexIndex) (c : Fin 3) : ℚ :=
  (rationalVerticesTable[i.val]'(by simp [rationalVerticesTable]))[c.val]'(by
    simp [rationalVerticesTable])

@[csimp] theorem rationalVertices_eq_impl : @rationalVertices = @rationalVerticesImpl := by
  funext i c
  simp [rationalVerticesImpl, rationalVerticesTable]

abbrev stlVertices := rationalVertices

def rationalVertex (i : VertexIndex) : Fin 3 → ℚ := rationalVertices i

def seedVertex : SeedIndex → Fin 3 → ℚ := ![
  ![95607336653427/2251799813685248, 2553994589029803/4503599627370496, 2543749016773927/4503599627370496],
  ![-208438279230124513419938539900593729786333151670672382452695213771090003193121/1224076267873291663352087115250153476427671495980998537313412680646657006632960, 57448722305781971304474826913106443457274909479993890866304180896460827989341/61203813393664583167604355762507673821383574799049926865670634032332850331648, 367115662294595894988744286384259356731936051817244634113235267091647325950663/1224076267873291663352087115250153476427671495980998537313412680646657006632960],
  ![-1259122882292673/4503599627370496, 1003756700517363/1125899906842624, -189740010677929/4503599627370496],
  ![129357367826243/2251799813685248, 1354183983942773/2251799813685248, -1718020733186383/2251799813685248]
]

def orbitIndex (i : VertexIndex) : OrbitIndex :=
  ⟨i.val / 4, by omega⟩

def seedIndex (i : VertexIndex) : SeedIndex :=
  ⟨i.val % 4, Nat.mod_lt _ (by omega)⟩

/-- The vertex ordering is rotation-major: four seeds for each of five orbits. -/
def indexEquiv : VertexIndex ≃ OrbitIndex × SeedIndex where
  toFun i := (orbitIndex i, seedIndex i)
  invFun ks := ⟨4 * ks.1.val + ks.2.val, by omega⟩
  left_inv i := by
    apply Fin.ext
    simp [orbitIndex, seedIndex]
    omega
  right_inv ks := by
    rcases ks with ⟨k, s⟩
    apply Prod.ext <;> apply Fin.ext <;> simp [orbitIndex, seedIndex] <;> omega

def vertexIndex (k : OrbitIndex) (s : SeedIndex) : VertexIndex :=
  indexEquiv.symm (k, s)

@[simp] theorem orbitIndex_vertexIndex (k : OrbitIndex) (s : SeedIndex) :
    orbitIndex (vertexIndex k s) = k := by
  exact congrArg Prod.fst (indexEquiv.apply_symm_apply (k, s))

@[simp] theorem seedIndex_vertexIndex (k : OrbitIndex) (s : SeedIndex) :
    seedIndex (vertexIndex k s) = s := by
  exact congrArg Prod.snd (indexEquiv.apply_symm_apply (k, s))

/-- A rational trigonometric approximation to the intended exact orbit vertex.
Angles in the second half of the orbit are reduced modulo `2π`, keeping their
absolute values below `π`. -/
def taylorVertex (i : VertexIndex) : Fin 3 → ℚ :=
  let k := orbitIndex i
  let k' : ℚ := if k.val ≤ 2 then k.val else k.val - 5
  let θ : ℚ := 2 * Noperthedron.piQ * k' / 5
  let c := RationalApprox.cosℚ θ
  let s := RationalApprox.sinℚ θ
  let v := seedVertex (seedIndex i)
  ![c * v 0 - s * v 1, s * v 0 + c * v 1, v 2]

def rationalPolyhedron : Polyhedron VertexIndex (Fin 3 → ℚ) :=
  ⟨rationalVertex⟩

noncomputable def exactVertex (i : VertexIndex) : ℝ³ :=
  RzL (2 * Real.pi * (orbitIndex i : ℝ) / 5) (toR3 (seedVertex (seedIndex i)))

noncomputable def exactPolyhedron : Polyhedron VertexIndex ℝ³ :=
  ⟨exactVertex⟩

noncomputable def exactVerts : Finset ℝ³ :=
  Finset.image exactVertex Finset.univ

theorem exactPolyhedron_hull :
    exactPolyhedron.hull = convexHull ℝ exactVerts := by
  simp only [Polyhedron.hull, exactPolyhedron, exactVerts, Finset.coe_image,
    Finset.coe_univ, Set.image_univ]
  congr 1

@[simp] theorem exactPolyhedron_vertex (i : VertexIndex) :
    exactPolyhedron.v i = exactVertex i := rfl

theorem exactVertex_norm_pos (i : VertexIndex) : 0 < ‖exactVertex i‖ := by
  rw [exactVertex, Bounding.Rz_preserves_norm, norm_pos_iff]
  intro h
  have hcoord := congrFun (congrArg WithLp.ofLp h) (2 : Fin 3)
  fin_cases i <;>
    simp [seedIndex, seedVertex, toR3] at hcoord

theorem exactVertex_norm_le_one (i : VertexIndex) : ‖exactVertex i‖ ≤ 1 := by
  rw [exactVertex, Bounding.Rz_preserves_norm]
  rw [← sq_le_sq₀ (norm_nonneg _) (by norm_num : (0 : ℝ) ≤ 1)]
  simp only [PiLp.norm_sq_eq_of_L2, Fin.sum_univ_three,
    Real.norm_eq_abs, sq_abs, one_pow]
  fin_cases i <;>
    simp [seedIndex, seedVertex, toR3] <;>
    norm_num

noncomputable def exactGoodPoly : GoodPoly VertexIndex where
  vertices := exactPolyhedron
  nontriv := exactVertex_norm_pos
  vertex_radius_le_one := exactVertex_norm_le_one

/-! ### Fivefold-symmetric models near the rational vertices

The certificates are checked against `rationalVertex`. What they need from
the real polyhedron is only exact fivefold symmetry about z and a per-vertex
distance bound, so they cover every `C5Model` below, not just `exactVertex`. -/

/-- The per-vertex distance the certificates allow between a model vertex and
`rationalVertex` (`TightApproximation.tightVertexErrorQ` has this value). -/
def modelErrorQ : ℚ := 6 / 10^16

/-- A polyhedron with exact fivefold symmetry about z, near the rational
model: vertex `i` is seed `seedIndex i` rotated by `2π · orbitIndex i / 5`,
and each vertex is within `modelErrorQ` of `rationalVertex i`. -/
structure C5Model where
  seed : SeedIndex → ℝ³
  close : ∀ i : VertexIndex,
    ‖RzL (2 * Real.pi * (orbitIndex i : ℝ) / 5) (seed (seedIndex i)) -
      toR3 (rationalVertex i)‖ ≤ (modelErrorQ : ℝ)

/-- Every rational vertex has norm in `[1/10, 1 - 10⁻¹²]`. -/
theorem rationalVertex_sq_norm_bounds : ∀ i : VertexIndex,
    (1 / 100 : ℚ) ≤ rationalVertex i 0 ^ 2 + rationalVertex i 1 ^ 2 + rationalVertex i 2 ^ 2 ∧
      rationalVertex i 0 ^ 2 + rationalVertex i 1 ^ 2 + rationalVertex i 2 ^ 2 ≤
        (1 - 1 / 10^12) ^ 2 := by
  decide +kernel

theorem norm_toR3_rationalVertex (i : VertexIndex) :
    1 / 10 ≤ ‖toR3 (rationalVertex i)‖ ∧ ‖toR3 (rationalVertex i)‖ ≤ 1 - 1 / 10^12 := by
  obtain ⟨hlo, hhi⟩ := rationalVertex_sq_norm_bounds i
  set q : ℚ := rationalVertex i 0 ^ 2 + rationalVertex i 1 ^ 2 + rationalVertex i 2 ^ 2
  have hsq : ‖toR3 (rationalVertex i)‖ ^ 2 = (q : ℝ) := by
    rw [EuclideanSpace.norm_eq, Real.sq_sqrt (by positivity)]
    simp only [Fin.sum_univ_three, Real.norm_eq_abs, sq_abs, toR3, q]
    push_cast
    ring
  have hlo' : (((1 / 100 : ℚ)) : ℝ) ≤ (q : ℝ) := Rat.cast_le.mpr hlo
  have hhi' : (q : ℝ) ≤ (((1 - 1 / 10^12) ^ 2 : ℚ) : ℝ) := Rat.cast_le.mpr hhi
  push_cast at hlo' hhi'
  have hn := norm_nonneg (toR3 (rationalVertex i))
  constructor <;> nlinarith

namespace C5Model

variable (P : C5Model)

/-- Vertex `i`: seed `seedIndex i` rotated by `2π · orbitIndex i / 5`. -/
noncomputable def vertex (i : VertexIndex) : ℝ³ :=
  RzL (2 * Real.pi * (orbitIndex i : ℝ) / 5) (P.seed (seedIndex i))

noncomputable def polyhedron : Polyhedron VertexIndex ℝ³ :=
  ⟨P.vertex⟩

noncomputable def verts : Finset ℝ³ :=
  Finset.image P.vertex Finset.univ

theorem polyhedron_hull : P.polyhedron.hull = convexHull ℝ P.verts := by
  simp only [Polyhedron.hull, polyhedron, verts, Finset.coe_image,
    Finset.coe_univ, Set.image_univ]
  congr 1

@[simp] theorem polyhedron_vertex (i : VertexIndex) : P.polyhedron.v i = P.vertex i := rfl

theorem vertex_close_model (i : VertexIndex) :
    ‖P.vertex i - toR3 (rationalVertex i)‖ ≤ (modelErrorQ : ℝ) :=
  P.close i

theorem vertex_norm_pos (i : VertexIndex) : 0 < ‖P.vertex i‖ := by
  have h := norm_sub_norm_le (toR3 (rationalVertex i)) (P.vertex i)
  rw [norm_sub_rev] at h
  have hc := P.vertex_close_model i
  have hr := (norm_toR3_rationalVertex i).1
  norm_num [modelErrorQ] at hc
  linarith

theorem vertex_norm_le_one (i : VertexIndex) : ‖P.vertex i‖ ≤ 1 := by
  have h := norm_le_norm_add_norm_sub' (P.vertex i) (toR3 (rationalVertex i))
  have hc := P.vertex_close_model i
  have hr := (norm_toR3_rationalVertex i).2
  norm_num [modelErrorQ] at hc
  linarith

noncomputable def goodPoly : GoodPoly VertexIndex where
  vertices := P.polyhedron
  nontriv := P.vertex_norm_pos
  vertex_radius_le_one := P.vertex_norm_le_one

end C5Model

end Noperthedron.Nopert231

end
