module

public import Noperthedron.Nopert231.AtlasProjectiveView

@[expose] public section

/-!
# Covering the upper view wedge by triangles

The identity-tube certificates are organized by face-visibility code: each
code cell of the upper view wedge is split into projective triangles, and
each triangle gets its own certificate table. This file provides the
missing link: a checkable certificate that a given list of triangles covers
`upperWedgeTriangle`.

All triangles here lie in the affine plane `u 0 + u 1 + u 2 = 1`. The
certificate is a decision tree over half-spaces `u ⬝ a ≥ 0` (the "path
constraints"), starting from the three edge functionals of the wedge:

* `split n pos neg` branches on `u ⬝ n ≥ 0` / `u ⬝ n ≤ 0`; every point takes
  at least one branch (`le_total`), so boundaries need no special care;
* `empty lam κ` proves that no point of the plane satisfies the path:
  `∑ lam_k a_k + κ (1,1,1) = 0` with `lam ≥ 0`, `κ > 0`;
* `leaf t certs` proves that every point satisfying the path lies in
  triangle `t`: each (oriented) edge functional `e_i` of the triangle is
  `∑ μ_k a_k + κ (1,1,1)` with `μ, κ ≥ 0`, hence `u ⬝ e_i ≥ 0`, and
  Cramer's rule turns those three inequalities into barycentric weights.

The tree is generated by `scripts/nopert231_emit_wedge_cover.py`.
-/

namespace Noperthedron.Nopert231.WedgeCover

open Noperthedron.SnubCube.ProjectiveView
open AtlasProjectiveView (upperWedgeTriangle)

abbrev V := Fin 3 → ℚ
abbrev Tri := Fin 3 → V

def dotQ (a b : V) : ℚ := a 0 * b 0 + a 1 * b 1 + a 2 * b 2

def crossQ (a b : V) : V :=
  ![a 1 * b 2 - a 2 * b 1, a 2 * b 0 - a 0 * b 2, a 0 * b 1 - a 1 * b 0]

def detQ (a b c : V) : ℚ := dotQ a (crossQ b c)

def sumVec : V := ![1, 1, 1]

def vecEq (a b : V) : Bool := a 0 = b 0 && a 1 = b 1 && a 2 = b 2

/-- Orientation sign of a triangle (`1` if counterclockwise). -/
def orient (t : Tri) : ℚ := if 0 < detQ (t 0) (t 1) (t 2) then 1 else -1

/-- Edge functionals of a triangle, oriented so that the triangle's cone is
where all three are nonnegative. -/
def edgeFn (t : Tri) (i : Fin 3) : V :=
  orient t • crossQ (t (i + 1)) (t (i + 2))

/-- `∑ lam_k • cs_k` (extra entries of either list are ignored). -/
def combo : List V → List ℚ → V
  | a :: as, l :: ls => l • a + combo as ls
  | _, _ => 0

inductive Node where
  | split (n : V) (pos neg : Node)
  | empty (lam : List ℚ) (kappa : ℚ)
  | leaf (tri : ℕ) (certs : List (List ℚ × ℚ))

/-- Decidable check of a cover tree, given the path constraints `cs`. -/
def Node.check (tris : Array Tri) : List V → Node → Bool
  | cs, .split n pos neg => pos.check tris (cs ++ [n]) && neg.check tris (cs ++ [-n])
  | cs, .empty lam kappa =>
      lam.length == cs.length && lam.all (fun x => decide (0 ≤ x)) &&
        decide (0 < kappa) && vecEq (combo cs lam + kappa • sumVec) 0
  | cs, .leaf t certs =>
      match tris[t]? with
      | none => false
      | some tri =>
          decide (detQ (tri 0) (tri 1) (tri 2) ≠ 0) &&
          decide (dotQ (tri 0) sumVec = 1) && decide (dotQ (tri 1) sumVec = 1) &&
          decide (dotQ (tri 2) sumVec = 1) &&
          (List.finRange 3).all fun i =>
            match certs[i.val]? with
            | none => false
            | some (mu, k) =>
                mu.length == cs.length && mu.all (fun x => decide (0 ≤ x)) &&
                  decide (0 ≤ k) && vecEq (edgeFn tri i) (combo cs mu + k • sumVec)

/-! ## Soundness -/

/-- Real dot product of a point with a rational vector. -/
def dotR (u : Fin 3 → ℝ) (a : V) : ℝ :=
  u 0 * (a 0 : ℝ) + u 1 * (a 1 : ℝ) + u 2 * (a 2 : ℝ)

theorem vecEq_iff (a b : V) : vecEq a b = true ↔ a = b := by
  constructor
  · intro h
    simp only [vecEq, Bool.and_eq_true, decide_eq_true_eq] at h
    funext c
    fin_cases c
    · exact h.1.1
    · exact h.1.2
    · exact h.2
  · rintro rfl
    simp [vecEq]

theorem dotR_add (u : Fin 3 → ℝ) (a b : V) : dotR u (a + b) = dotR u a + dotR u b := by
  simp [dotR]; ring

theorem dotR_smul (u : Fin 3 → ℝ) (s : ℚ) (a : V) : dotR u (s • a) = (s : ℝ) * dotR u a := by
  simp [dotR]; ring

theorem dotR_neg (u : Fin 3 → ℝ) (a : V) : dotR u (-a) = -dotR u a := by
  simp [dotR]; ring

theorem dotR_zero (u : Fin 3 → ℝ) : dotR u 0 = 0 := by
  simp [dotR]

/-- If every path constraint holds and every coefficient is nonnegative, the
combination is nonnegative at `u`. -/
theorem dotR_combo_nonneg (u : Fin 3 → ℝ) :
    ∀ (cs : List V) (lam : List ℚ), (∀ a ∈ cs, 0 ≤ dotR u a) →
      (∀ x ∈ lam, 0 ≤ x) → 0 ≤ dotR u (combo cs lam)
  | a :: as, l :: ls, hcs, hlam => by
      simp only [combo, dotR_add, dotR_smul]
      have h1 : (0 : ℝ) ≤ l := by exact_mod_cast hlam l (by simp)
      have h2 : 0 ≤ dotR u a := hcs a (by simp)
      have h3 := dotR_combo_nonneg u as ls (fun b hb => hcs b (by simp [hb]))
        (fun x hx => hlam x (by simp [hx]))
      nlinarith [mul_nonneg h1 h2]
  | [], _, _, _ => by simp [combo, dotR_zero]
  | _ :: _, [], _, _ => by simp [combo, dotR_zero]

theorem dotR_sumVec (u : Fin 3 → ℝ) : dotR u sumVec = u 0 + u 1 + u 2 := by
  simp [dotR, sumVec]

/-- Cramer's rule: three nonnegative oriented edge values give barycentric
weights. -/
theorem inTriangle_of_edges (tri : Tri) (u : Fin 3 → ℝ)
    (hdet : detQ (tri 0) (tri 1) (tri 2) ≠ 0)
    (hs0 : dotQ (tri 0) sumVec = 1) (hs1 : dotQ (tri 1) sumVec = 1)
    (hs2 : dotQ (tri 2) sumVec = 1)
    (hsum : u 0 + u 1 + u 2 = 1)
    (hedge : ∀ i, 0 ≤ dotR u (edgeFn tri i)) :
    InTriangle (toReal tri) u := by
  set D : ℚ := detQ (tri 0) (tri 1) (tri 2) with hD
  set o : ℚ := orient tri with ho
  have hoD : 0 < o * D := by
    simp only [ho, orient, hD]
    split_ifs with h
    · simpa using h
    · have : D < 0 := lt_of_le_of_ne (not_lt.mp h) hdet
      simp only [hD] at this
      nlinarith
  have hoDR : (0 : ℝ) < (o : ℝ) * (D : ℝ) := by exact_mod_cast hoD
  -- Raw (unoriented) edge values.
  let r : Fin 3 → ℝ := fun i => dotR u (crossQ (tri (i + 1)) (tri (i + 2)))
  have hedge' : ∀ i, 0 ≤ (o : ℝ) * r i := by
    intro i
    have := hedge i
    simpa [edgeFn, dotR_smul, r] using this
  let weight : Fin 3 → ℝ := fun i => ((o : ℝ) * r i) / ((o : ℝ) * (D : ℝ))
  -- Cramer identity: D • u = ∑ r_i • tri_i, coordinatewise.
  have hcramer : ∀ c, (D : ℝ) * u c = ∑ i, r i * (tri i c : ℝ) := by
    intro c
    simp only [r, dotR, crossQ, hD, detQ, dotQ, Fin.sum_univ_three]
    fin_cases c <;>
      simp only [Fin.isValue, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val,
        Fin.reduceFinMk] <;> push_cast <;> ring
  have hDR : (D : ℝ) ≠ 0 := by exact_mod_cast hdet
  have hoR : (o : ℝ) ≠ 0 := by
    intro h0
    rw [h0, zero_mul] at hoDR
    exact lt_irrefl _ hoDR
  refine ⟨weight, ?_, ?_, ?_⟩
  · intro i
    exact div_nonneg (hedge' i) hoDR.le
  · -- ∑ weight = (∑ r_i) / D, and ∑ r_i = D (u ⬝ (1,1,1)) via the corner sums.
    have hsR : ∀ (i : Fin 3), dotQ (tri i) sumVec = 1 →
        (tri i 0 : ℝ) + (tri i 1 : ℝ) + (tri i 2 : ℝ) = 1 := by
      intro i h
      simp only [dotQ, sumVec, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_two,
        Matrix.head_cons, Matrix.tail_cons, mul_one] at h
      exact_mod_cast h
    have hrsum : r 0 + r 1 + r 2 = (D : ℝ) := by
      have h0 := hcramer 0
      have h1 := hcramer 1
      have h2 := hcramer 2
      simp only [Fin.sum_univ_three] at h0 h1 h2
      have hs0' := hsR 0 hs0
      have hs1' := hsR 1 hs1
      have hs2' := hsR 2 hs2
      have : (D : ℝ) * (u 0 + u 1 + u 2) =
          r 0 * ((tri 0 0 : ℝ) + tri 0 1 + tri 0 2) +
            r 1 * ((tri 1 0 : ℝ) + tri 1 1 + tri 1 2) +
            r 2 * ((tri 2 0 : ℝ) + tri 2 1 + tri 2 2) := by
        nlinarith [h0, h1, h2]
      rw [hsum, hs0', hs1', hs2'] at this
      linarith
    simp only [Fin.sum_univ_three, weight]
    rw [← add_div, ← add_div, ← mul_add, ← mul_add, hrsum]
    exact div_self hoDR.ne'
  · funext c
    simp only [affinePoint, toReal, weight]
    have := hcramer c
    rw [Fin.sum_univ_three] at this ⊢
    field_simp
    nlinarith [this]

/-- Soundness of the cover tree check. -/
theorem Node.sound (tris : Array Tri) (u : Fin 3 → ℝ)
    (hsum : u 0 + u 1 + u 2 = 1) :
    ∀ (node : Node) (cs : List V), node.check tris cs = true →
      (∀ a ∈ cs, 0 ≤ dotR u a) →
      ∃ t : ℕ, ∃ tri, tris[t]? = some tri ∧ InTriangle (toReal tri) u
  | .split n pos neg, cs, hcheck, hcs => by
      simp only [Node.check, Bool.and_eq_true] at hcheck
      rcases le_total 0 (dotR u n) with h | h
      · exact Node.sound tris u hsum pos (cs ++ [n]) hcheck.1 (by
          intro a ha
          rcases List.mem_append.mp ha with ha | ha
          · exact hcs a ha
          · simp at ha; subst ha; exact h)
      · exact Node.sound tris u hsum neg (cs ++ [-n]) hcheck.2 (by
          intro a ha
          rcases List.mem_append.mp ha with ha | ha
          · exact hcs a ha
          · simp at ha; subst ha; rw [dotR_neg]; linarith)
  | .empty lam kappa, cs, hcheck, hcs => by
      simp only [Node.check, Bool.and_eq_true, beq_iff_eq, List.all_eq_true,
        decide_eq_true_eq] at hcheck
      obtain ⟨⟨⟨_, hlam⟩, hk⟩, hzero⟩ := hcheck
      rw [vecEq_iff] at hzero
      have hnn := dotR_combo_nonneg u cs lam hcs hlam
      have hval : dotR u (combo cs lam + kappa • sumVec) = 0 := by
        rw [hzero, dotR_zero]
      rw [dotR_add, dotR_smul, dotR_sumVec, hsum] at hval
      have hkR : (0 : ℝ) < kappa := by exact_mod_cast hk
      linarith
  | .leaf t certs, cs, hcheck, hcs => by
      simp only [Node.check] at hcheck
      cases htri : tris[t]? with
      | none => simp [htri] at hcheck
      | some tri =>
        simp only [htri, Bool.and_eq_true, decide_eq_true_eq, List.all_eq_true,
          List.mem_finRange, true_implies] at hcheck
        obtain ⟨⟨⟨⟨hdet, hs0⟩, hs1⟩, hs2⟩, hcerts⟩ := hcheck
        refine ⟨t, tri, htri, inTriangle_of_edges tri u hdet hs0 hs1 hs2 hsum ?_⟩
        intro i
        have hi := hcerts i
        cases hc : certs[i.val]? with
        | none => simp [hc] at hi
        | some mk =>
          obtain ⟨mu, k⟩ := mk
          simp only [hc, Bool.and_eq_true, beq_iff_eq, List.all_eq_true,
            decide_eq_true_eq] at hi
          obtain ⟨⟨⟨_, hmu⟩, hk⟩, heq⟩ := hi
          rw [vecEq_iff] at heq
          rw [heq, dotR_add, dotR_smul, dotR_sumVec, hsum]
          have := dotR_combo_nonneg u cs mu hcs hmu
          have hkR : (0 : ℝ) ≤ k := by exact_mod_cast hk
          linarith

/-- The three (oriented) edge functionals of the wedge. -/
def wedgeConstraints : List V :=
  [edgeFn upperWedgeTriangle 0, edgeFn upperWedgeTriangle 1, edgeFn upperWedgeTriangle 2]

theorem wedge_constraints_hold (u : Fin 3 → ℝ)
    (hu : InTriangle (toReal upperWedgeTriangle) u) :
    (u 0 + u 1 + u 2 = 1) ∧ ∀ a ∈ wedgeConstraints, 0 ≤ dotR u a := by
  obtain ⟨w, hw, hws, rfl⟩ := hu
  have hw0 := hw 0
  have hw1 := hw 1
  have hw2 := hw 2
  rw [Fin.sum_univ_three] at hws
  constructor
  · simp [affinePoint, toReal, upperWedgeTriangle, Fin.sum_univ_three]
    linarith
  · intro a ha
    simp only [wedgeConstraints, List.mem_cons, List.not_mem_nil, or_false] at ha
    rcases ha with rfl | rfl | rfl <;>
      simp [dotR, edgeFn, orient, crossQ, detQ, dotQ, affinePoint, toReal,
        upperWedgeTriangle, Fin.sum_univ_three] <;> norm_num <;> nlinarith

/-- Main cover theorem: if the tree checks, every point of the wedge lies in
one of the triangles. -/
theorem wedge_covered (tris : Array Tri) (tree : Node)
    (hcheck : tree.check tris wedgeConstraints = true)
    (u : Fin 3 → ℝ) (hu : InTriangle (toReal upperWedgeTriangle) u) :
    ∃ t : ℕ, ∃ tri, tris[t]? = some tri ∧ InTriangle (toReal tri) u := by
  obtain ⟨hsum, hcs⟩ := wedge_constraints_hold u hu
  exact Node.sound tris u hsum tree wedgeConstraints hcheck hcs

end Noperthedron.Nopert231.WedgeCover
