name = "Noperthedron"
defaultTargets = ["Noperthedron"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.style.multiGoal = true
weak.linter.style.cdot = true

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "tryAtEachStep"
git = "https://github.com/dwrensha/tryAtEachStep"
rev = "main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "09178ce7676d92ddcfc6dafe90fdfa758e97002e"

[[lean_lib]]
name = "Noperthedron"

[[lean_exe]]
name = "constructValidTable"
root = "constructValidTable"
buildType = "release"