module

public import Noperthedron.RationalApprox.TrigLemmas
public import Noperthedron.Vertices.Taylor
public import Mathlib.Analysis.Real.Pi.Bounds

@[expose] public section

/-!
# Exact and rational vertices of Nopert #228

Candidate Nopert #228 is derived directly from the repair214 root construction,
tweaking ring 1 by an azimuth rotation of -10⁻³ radians and deriving the
z-coordinate of ring 1 algebraically to enforce exact coplanarity of the
quadrilateral face.

The vertices are scaled so that all vertices lie inside the unit sphere,
satisfying the GoodPoly invariant. The twenty vertices are generated by
rotating four seed vertices around the z-axis in increments of 2π/5.
-/

namespace Noperthedron.Nopert228

abbrev VertexIndex := Fin 20
abbrev SeedIndex := Fin 4
abbrev OrbitIndex := Fin 5

def rationalVertices : VertexIndex → Fin 3 → ℚ := ![
  ![214495956834651/5000000000000000, 2844207617087577/5000000000000000, 2835269632433251/5000000000000000],
  ![-1710709167057709/10000000000000000, 9382900786342319/10000000000000000, 3005768949769993/10000000000000000],
  ![-5469278670747/19531250000000, 4463776205866777/5000000000000000, -391914942198597/10000000000000000],
  ![291002402568799/5000000000000000, 3017006771332021/5000000000000000, -3826914744902991/5000000000000000],
  ![-5277438584081657/10000000000000000, 1082906266677293/5000000000000000, 2835269632433251/5000000000000000],
  ![-15123691423449/16000000000000, 636247349348873/5000000000000000, 3005768949769993/10000000000000000],
  ![-9355938124537131/10000000000000000, 3821989453749/400000000000000, -391914942198597/10000000000000000],
  ![-5558838523568443/10000000000000000, 96725287656519/400000000000000, -3826914744902991/5000000000000000],
  ![-1845314166085943/5000000000000000, -33983355275793/78125000000000, 2835269632433251/5000000000000000],
  ![-4131137917352767/10000000000000000, -1719291162408611/2000000000000000, 3005768949769993/10000000000000000],
  ![-2982017078182431/10000000000000000, -8868499427057041/10000000000000000, -391914942198597/10000000000000000],
  ![-4017555950675181/10000000000000000, -1134881414770139/2500000000000000, -3826914744902991/5000000000000000],
  ![599300966991219/2000000000000000, -4854179715716587/10000000000000000, 2835269632433251/5000000000000000],
  ![6899123494518161/10000000000000000, -6585396573326933/10000000000000000, 3005768949769993/10000000000000000],
  ![7512950215187737/10000000000000000, -1115316762294789/2000000000000000, -391914942198597/10000000000000000],
  ![1537926197173393/5000000000000000, -1305928335381757/2500000000000000, -3826914744902991/5000000000000000],
  ![5542570167628147/10000000000000000, 26996428469767/200000000000000, 2835269632433251/5000000000000000],
  ![419751536477397/500000000000000, 14145177813531/31250000000000, 3005768949769993/10000000000000000],
  ![7625275666954289/10000000000000000, 2710990545226853/5000000000000000, -391914942198597/10000000000000000],
  ![147963431868981/250000000000000, 655546633265283/5000000000000000, -3826914744902991/5000000000000000]
]

abbrev stlVertices := rationalVertices

def rationalVertex (i : VertexIndex) : Fin 3 → ℚ := rationalVertices i

def seedVertex : SeedIndex → Fin 3 → ℚ := ![
  ![214495956834651/5000000000000000, 2844207617087577/5000000000000000, 2835269632433251/5000000000000000],
  ![-1710709167057709/10000000000000000, 9382900786342319/10000000000000000, 3005768949769993/10000000000000000],
  ![-5469278670747/19531250000000, 4463776205866777/5000000000000000, -391914942198597/10000000000000000],
  ![291002402568799/5000000000000000, 3017006771332021/5000000000000000, -3826914744902991/5000000000000000]
]

def orbitIndex (i : VertexIndex) : OrbitIndex :=
  ⟨i.val / 4, by omega⟩

def seedIndex (i : VertexIndex) : SeedIndex :=
  ⟨i.val % 4, Nat.mod_lt _ (by omega)⟩

/-- The vertex ordering is rotation-major: four seeds for each of five orbits. -/
def indexEquiv : VertexIndex ≃ OrbitIndex × SeedIndex where
  toFun i := (orbitIndex i, seedIndex i)
  invFun ks := ⟨4 * ks.1.val + ks.2.val, by omega⟩
  left_inv i := by
    apply Fin.ext
    simp [orbitIndex, seedIndex]
    omega
  right_inv ks := by
    rcases ks with ⟨k, s⟩
    apply Prod.ext <;> apply Fin.ext <;> simp [orbitIndex, seedIndex] <;> omega

def vertexIndex (k : OrbitIndex) (s : SeedIndex) : VertexIndex :=
  indexEquiv.symm (k, s)

@[simp] theorem orbitIndex_vertexIndex (k : OrbitIndex) (s : SeedIndex) :
    orbitIndex (vertexIndex k s) = k := by
  exact congrArg Prod.fst (indexEquiv.apply_symm_apply (k, s))

@[simp] theorem seedIndex_vertexIndex (k : OrbitIndex) (s : SeedIndex) :
    seedIndex (vertexIndex k s) = s := by
  exact congrArg Prod.snd (indexEquiv.apply_symm_apply (k, s))

/-- A rational trigonometric approximation to the intended exact orbit vertex.
Angles in the second half of the orbit are reduced modulo `2π`, keeping their
absolute values below `π`. -/
def taylorVertex (i : VertexIndex) : Fin 3 → ℚ :=
  let k := orbitIndex i
  let k' : ℚ := if k.val ≤ 2 then k.val else k.val - 5
  let θ : ℚ := 2 * Noperthedron.piQ * k' / 5
  let c := RationalApprox.cosℚ θ
  let s := RationalApprox.sinℚ θ
  let v := seedVertex (seedIndex i)
  ![c * v 0 - s * v 1, s * v 0 + c * v 1, v 2]

def rationalPolyhedron : Polyhedron VertexIndex (Fin 3 → ℚ) :=
  ⟨rationalVertex⟩

noncomputable def exactVertex (i : VertexIndex) : ℝ³ :=
  RzL (2 * Real.pi * (orbitIndex i : ℝ) / 5) (toR3 (seedVertex (seedIndex i)))

noncomputable def exactPolyhedron : Polyhedron VertexIndex ℝ³ :=
  ⟨exactVertex⟩

noncomputable def exactVerts : Finset ℝ³ :=
  Finset.image exactVertex Finset.univ

theorem exactPolyhedron_hull :
    exactPolyhedron.hull = convexHull ℝ exactVerts := by
  simp only [Polyhedron.hull, exactPolyhedron, exactVerts, Finset.coe_image,
    Finset.coe_univ, Set.image_univ]
  congr 1

@[simp] theorem exactPolyhedron_vertex (i : VertexIndex) :
    exactPolyhedron.v i = exactVertex i := rfl

theorem exactVertex_norm_pos (i : VertexIndex) : 0 < ‖exactVertex i‖ := by
  rw [exactVertex, Bounding.Rz_preserves_norm, norm_pos_iff]
  intro h
  have hcoord := congrFun (congrArg WithLp.ofLp h) (2 : Fin 3)
  fin_cases i <;>
    simp [seedIndex, seedVertex, toR3] at hcoord <;>
    norm_num at hcoord

theorem exactVertex_norm_le_one (i : VertexIndex) : ‖exactVertex i‖ ≤ 1 := by
  rw [exactVertex, Bounding.Rz_preserves_norm]
  rw [← sq_le_sq₀ (norm_nonneg _) (by norm_num : (0 : ℝ) ≤ 1)]
  simp only [PiLp.norm_sq_eq_of_L2, Fin.sum_univ_three,
    Real.norm_eq_abs, sq_abs, one_pow]
  fin_cases i <;>
    simp [seedIndex, seedVertex, toR3] <;>
    norm_num

noncomputable def exactGoodPoly : GoodPoly VertexIndex where
  vertices := exactPolyhedron
  nontriv := exactVertex_norm_pos
  vertex_radius_le_one := exactVertex_norm_le_one

end Noperthedron.Nopert228

end
