import Noperthedron.SolutionTable.RationalLocalCheck.Computable.BasicChecks
import Noperthedron.SolutionTable.RationalLocalCheck.Computable.Oracle
import Noperthedron.SolutionTable.RationalLocalCheck.Computable.Bool
