#!/usr/bin/env python3
"""Generate DHStatementData.lean: the exact deltoidal hexecontahedron.

Reads nopert229's dh_exact.txt (written by dh_exact.py from dh_model.txt):
- `kvertex <slot> ...`: the 70 vertex slots' coordinates in the model frame,
  unscaled (McCooey's scale), in K = Q(sqrt5, s), s = sin 72 degrees, each
  coordinate as a + b sqrt5 + c s + d s sqrt5;
- `frame_e1/e2/e3`: the rows of the rotation T from McCooey's frame to the
  model frame (slot = T * McCooey vertex);
- `scale`: a rational within 10^-45 of the model's scale (the rational model
  is scale * slot, rounded to 2^-64).

Lean (DHStatement.lean) re-decides everything it uses: T orthonormal, T maps
McCooey's 62 vertices onto the slots, the slots are the I-orbits of the base
slots with the model's stabilizers, and scale * slot is within modelErrorQ of
rationalVertex.

Usage: python3 scripts/dh_statement_data.py [--model_dir DIR] [--out FILE]
(--model_dir defaults to $MODEL_DIR, the C++ pipeline directory.)
"""

import argparse
import os
from fractions import Fraction as F
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent


def q(x: F) -> str:
    if x.denominator == 1:
        return f"({x.numerator} : ℚ)"
    return f"({x.numerator} / {x.denominator} : ℚ)"


def kq(t: list[F]) -> str:
    return "⟨" + ", ".join(q(x) for x in t) + "⟩"


def kvec(cs: list[list[F]]) -> str:
    return "![" + ", ".join(kq(c) for c in cs) + "]"


def parse_k(tokens: list[str]) -> list[list[F]]:
    vals = [F(t) for t in tokens]
    assert len(vals) == 12
    return [vals[4 * i:4 * i + 4] for i in range(3)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model_dir", type=Path,
                    default=Path(os.environ["MODEL_DIR"]) if os.environ.get("MODEL_DIR") else None)
    ap.add_argument("--out", type=Path, default=REPO / "Noperthedron/PentagonalHexecontahedron/DHStatementData.lean")
    args = ap.parse_args()
    if args.model_dir is None:
        raise SystemExit("pass --model_dir or set MODEL_DIR to the C++ pipeline directory")
    slots, frame, scale = {}, {}, None
    for line in (args.model_dir / "dh_exact.txt").read_text().splitlines():
        t = line.split()
        if not t or t[0].startswith("#"):
            continue
        if t[0] == "kvertex":
            slots[int(t[1])] = parse_k(t[2:])
        elif t[0].startswith("frame_e"):
            frame[int(t[0][-1])] = parse_k(t[1:])
        elif t[0] == "scale":
            scale = F(t[1])
    assert sorted(slots) == list(range(70)) and sorted(frame) == [1, 2, 3] and scale is not None
    out = []
    w = out.append
    w("module\n\npublic import Noperthedron.PentagonalHexecontahedron.CapPoly\n\n@[expose] public section\n")
    w("/-!\n# The exact deltoidal hexecontahedron (generated)\n\n"
      "Generated by `scripts/dh_statement_data.py` from nopert229's `dh_exact.txt`; do not\n"
      "edit. DHStatement.lean checks all of it.\n-/\n")
    w("namespace Noperthedron.PentagonalHexecontahedron.DH\n\nopen NPoly PVec\n")
    w("/-- The 70 vertex slots in the model frame, unscaled (McCooey's scale), over K. -/")
    w("def dhSlotK : Array KVec := #[\n" + ",\n".join("  " + kvec(slots[i]) for i in range(70)) + "]\n")
    w("/-- The rows of the rotation from McCooey's frame to the model frame. -/")
    w("def dhFrameK : Array KVec := #[\n" + ",\n".join("  " + kvec(frame[i]) for i in (1, 2, 3)) + "]\n")
    w("/-- The model's scale (rational, within 10⁻⁴⁵). -/")
    w(f"def dhScale : ℚ := {scale.numerator} / {scale.denominator}\n")
    w("end Noperthedron.PentagonalHexecontahedron.DH")
    args.out.write_text("\n".join(out) + "\n")
    print(f"wrote {args.out}: 70 slots, frame, scale {float(scale):.15f}")


if __name__ == "__main__":
    main()
