import Noperthedron.Checker.SqrtDvLiterals

/-! Generator for `Noperthedron/Checker/SqrtDvNat.lean`: the 8,100 pairwise
vertex-difference norms (`sqrtDvCurriedN`, scale `10¹⁶`, all nonnegative and
`< 2⁵⁷`) packed into a single `Nat` literal with 57-bit binary fields, for
the kernel-only fast local checker. An access is one accelerated shift +
mask instead of a ~40-cell curried walk.

Run from the repo root:
  lake env lean --run scripts/gen_sqrtdv_nat.lean > Noperthedron/Checker/SqrtDvNat.lean
-/

open Noperthedron.Solution

/-- Flat pair index, matching `sqrtDvTable`'s layout:
`flat a * 90 + flat b` with `flat = 45ℓ + 15i + k`. -/
def encTable : ℕ :=
  (List.finRange 8100).foldr (init := 0) fun j acc =>
    let fa := j.val / 90
    let fb := j.val % 90
    (sqrtDvCurriedN ⟨fa / 45, by omega⟩ ⟨fa / 15 % 3, by omega⟩ ⟨fa % 15, by omega⟩
      ⟨fb / 45, by omega⟩ ⟨fb / 15 % 3, by omega⟩ ⟨fb % 15, by omega⟩).toNat
      + (acc <<< 57)

def main : IO Unit := do
  IO.println "import Noperthedron.Checker.SqrtDvLiterals"
  IO.println ""
  IO.println "/-! # Packed pair-norm table (GENERATED)"
  IO.println ""
  IO.println "GENERATED by `scripts/gen_sqrtdv_nat.lean` — do not edit."
  IO.println ""
  IO.println "The 8,100 scale-`10¹⁶` pairwise vertex-difference norms of"
  IO.println "`sqrtDvCurriedN`, packed into one `Nat` literal: the pair"
  IO.println "`(a, b)` occupies the 57-bit field at offset"
  IO.println "`57 * (flat a * 90 + flat b)` with `flat = 45ℓ + 15i + k` — i.e."
  IO.println "row `a` is the 5,130-bit block at offset `5130 * flat a`, which the"
  IO.println "fast checker pre-shifts once per `i`. All"
  IO.println "entries are nonnegative and `< 2⁵⁷`, so no offset encoding is"
  IO.println "needed. Under `decide +kernel` an access is one accelerated"
  IO.println "shift + mask; `sqrtDvBig_spec` (proved by the kernel itself)"
  IO.println "certifies every field against `sqrtDvCurriedN`, in exactly the"
  IO.println "shape the fast local checker reads. -/"
  IO.println ""
  IO.println "namespace Noperthedron.Solution"
  IO.println ""
  IO.println s!"def sqrtDvBig : ℕ := {encTable}"
  IO.println ""
  IO.println "set_option maxRecDepth 10000 in"
  IO.println "theorem sqrtDvBig_spec :"
  IO.println "    ∀ (ℓa : Fin 2) (ia : Fin 3) (ka : Fin 15) (ℓb : Fin 2) (ib : Fin 3) (kb : Fin 15),"
  IO.println "      (let rowT := Nat.land (Nat.shiftRight sqrtDvBig"
  IO.println "        (Nat.mul 5130 (45 * ℓa.val + 15 * ia.val + ka.val))) (2 ^ 5130 - 1)"
  IO.println "       ((Nat.land (Nat.shiftRight rowT"
  IO.println "          (Nat.mul 57 (45 * ℓb.val + 15 * ib.val + kb.val))) (2 ^ 57 - 1) : ℕ) : ℤ))"
  IO.println "        = sqrtDvCurriedN ℓa ia ka ℓb ib kb := by"
  IO.println "  decide +kernel"
  IO.println ""
  IO.println "end Noperthedron.Solution"
