#!/usr/bin/env python3
"""
Generate rational approximate noperthedron vertices for Lean.

Uses the 13-term Taylor partial sums (sinℚ/cosℚ) evaluated at 2πk/15
with sufficient precision to match the Lean definitions exactly.
"""

from fractions import Fraction
import math

# The three basis vertices (from Nopert.lean)
C1 = [Fraction(152024884, 259375205), Fraction(0, 1), Fraction(210152163, 259375205)]
C2 = [Fraction(6632738028, 10**10), Fraction(6106948881, 10**10), Fraction(3980949609, 10**10)]
C3 = [Fraction(8193990033, 10**10), Fraction(5298215096, 10**10), Fraction(1230614493, 10**10)]
basis = [C1, C2, C3]

def sin_psum(n, x):
    """13-term Taylor partial sum for sin (matching sinℚ in Lean)."""
    result = Fraction(0)
    for i in range(n):
        sign = (-1)**i
        power = 2*i + 1
        factorial = math.factorial(power)
        result += Fraction(sign, 1) * x**power / Fraction(factorial, 1)
    return result

def cos_psum(n, x):
    """13-term Taylor partial sum for cos (matching cosℚ in Lean)."""
    result = Fraction(0)
    for i in range(n):
        sign = (-1)**i
        power = 2*i
        factorial = math.factorial(power)
        result += Fraction(sign, 1) * x**power / Fraction(factorial, 1)
    return result

def sinQ(x):
    return sin_psum(13, x)

def cosQ(x):
    return cos_psum(13, x)

# We can't use exact π in Fraction. Instead, use a very high precision
# rational approximation of π. The sinℚ/cosℚ proof in Lean uses the
# SYMBOLIC 2πk/15, not a numerical approximation.
#
# For generating the lookup table, we evaluate at high-precision π
# and round to match what Lean would compute.
#
# Actually, the right approach: the Lean sinℚ/cosℚ are polynomial
# functions of their input. We need to evaluate the POLYNOMIAL at
# a specific value of π. We'll use mpmath for exact arithmetic.

try:
    import mpmath
    mpmath.mp.dps = 200  # 200 decimal digits
    pi = mpmath.mpf(mpmath.pi)
except ImportError:
    # Fallback: use decimal module
    from decimal import Decimal, getcontext
    getcontext().prec = 200
    pi = Decimal('3.14159265358979323846264338327950288419716939937510'
                 '58209749445923078164062862089986280348253421170679'
                 '82148086513282306647093844609550582231725359408128'
                 '48111745028410270193852110555964462294895493038196')

print("-- Generated by scripts/gen_approx_vertices.py")
print("-- Rational approximate vertices for the noperthedron")
print()

# For each k = 0..14, compute cosQ(2πk/15) and sinQ(2πk/15)
# as rational numbers (using Fraction with a rational approx of π)

# Use a very precise rational approximation of π
# π ≈ 245850922/78256779 (good to ~18 digits)
# For κ = 10^{-10} accuracy we need more precision
# Let's use the convergent with ~50 digit accuracy
from decimal import Decimal, getcontext
getcontext().prec = 100

# Actually, for THIS script we just need to OUTPUT the rational values.
# The PROOF that they approximate the real vertices is done in Lean.
# So we can use floating point to compute them and then find close rationals.

# Better approach: since sinℚ is a degree-25 polynomial, and we're evaluating
# at x = 2πk/15, we can compute this symbolically with a rational approx of π.

# Use 10^50-precision rational for π
PI_NUM = 314159265358979323846264338327950288419716939937510
PI_DEN = 10**50
PI = Fraction(PI_NUM, PI_DEN)

for k in range(15):
    angle = 2 * PI * k / 15
    c = cosQ(angle)
    s = sinQ(angle)
    print(f"-- k={k}: angle=2π·{k}/15")
    print(f"--   cos ≈ {float(c):.15f}")
    print(f"--   sin ≈ {float(s):.15f}")

    for idx, (name, basis_pt) in enumerate(zip(["C1", "C2", "C3"], basis)):
        # Rz(θ) · v = [cos θ · vx - sin θ · vy, sin θ · vx + cos θ · vy, vz]
        vx, vy, vz = basis_pt
        rx = c * vx - s * vy
        ry = s * vx + c * vy
        rz = vz
        print(f"--   Rz·{name} = [{float(rx):.10f}, {float(ry):.10f}, {float(rz):.10f}]")

print()
print(f"-- Total: {15 * 3 * 2} vertices (15 rotations × 3 basis × 2 parities)")
print(f"-- Each parity-1 vertex is just the negation, so 45 unique vectors needed")
