import Noperthedron.Vertices.PythonInt

/-! Generator for `Noperthedron/Vertices/PythonNat.lean`: the 90×3 integer
vertex table packed into a single `Nat` literal with 57-bit binary fields
(offset-encoded, `coord + 2^56`), for the kernel-only fast checkers. A vertex
access is one accelerated shift + mask instead of a ~20-cell curried walk.

Run from the repo root:
  lake env lean --run scripts/gen_python_nat.lean > Noperthedron/Vertices/PythonNat.lean
-/

open Noperthedron

def offF : ℤ := 2 ^ 56

/-- 171-bit block for flat vertex `j` (`flat = 45ℓ + 15i + k`, the
`VertexIndex.ofFin90` order): the three offset coordinates in 57-bit fields,
little-endian. -/
def encVertex (j : Fin 90) : ℕ :=
  let idx := VertexIndex.ofFin90 j
  let f (c : Fin 3) : ℕ := (pythonVertexNum idx c + offF).toNat
  f 0 + (f 1 <<< 57) + (f 2 <<< 114)

def encTable : ℕ :=
  (List.finRange 90).foldr (fun j acc => encVertex j + (acc <<< 171)) 0

def main : IO Unit := do
  IO.println "import Noperthedron.Vertices.PythonInt"
  IO.println ""
  IO.println "/-! # Packed integer vertex table (GENERATED)"
  IO.println ""
  IO.println "GENERATED by `scripts/gen_python_nat.lean` — do not edit."
  IO.println ""
  IO.println "The 90×3 scale-`10¹⁶` vertex coordinates of `pythonVertexNum`, packed"
  IO.println "into one `Nat` literal: flat vertex `j = 45ℓ + 15i + k` occupies bits"
  IO.println "`[171j, 171(j+1))`, coordinate `c` the 57-bit field at offset `57c`,"
  IO.println "offset-encoded as `coord + 2^56` (so all fields are nonnegative and"
  IO.println "`< 2^57`). Under `decide +kernel` a vertex access is one accelerated"
  IO.println "shift + mask; `pythonVertexBig_spec` (proved by the kernel itself)"
  IO.println "certifies every field against `pythonVertexNum`, in exactly the"
  IO.println "`let`-shape the fast checkers use. -/"
  IO.println ""
  IO.println "namespace Noperthedron"
  IO.println ""
  IO.println s!"def pythonVertexBig : ℕ := {encTable}"
  IO.println ""
  IO.println "set_option maxRecDepth 10000 in"
  IO.println "theorem pythonVertexBig_spec :"
  IO.println "    ∀ j : Fin 90,"
  IO.println "      let v := (pythonVertexBig >>> (171 * j.val)) &&& (2 ^ 171 - 1)"
  IO.println "      ((v &&& (2 ^ 57 - 1) : ℕ) : ℤ)"
  IO.println "          = pythonVertexNum (VertexIndex.ofFin90 j) 0 + 2 ^ 56 ∧"
  IO.println "        (((v >>> 57) &&& (2 ^ 57 - 1) : ℕ) : ℤ)"
  IO.println "          = pythonVertexNum (VertexIndex.ofFin90 j) 1 + 2 ^ 56 ∧"
  IO.println "        ((v >>> 114 : ℕ) : ℤ)"
  IO.println "          = pythonVertexNum (VertexIndex.ofFin90 j) 2 + 2 ^ 56 := by"
  IO.println "  decide +kernel"
  IO.println ""
  IO.println "end Noperthedron"
