#!/usr/bin/env python3
"""Install new exact rational vertices into Noperthedron/Nopert229/Vertices.lean.

Reads the rational vertex list exported by nopert229/codebdd229.cc
(vertices229_exact27.lean, by default next to this repository) and rewrites
the bodies of `rationalVertices` (all 20 rows) and `seedVertex` (the first
four rows, i.e. orbit 0) in Vertices.lean. Vertex order is rotation-major
(index = 4 * orbit + seed), as generated by codebdd229.

After this, regenerate the tangent cones with
  python3 scripts/nopert229_emit_tangent_cones.py Noperthedron/Nopert229/GeneratedTangentCones.lean
and rebuild.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent


def read_rows(exported: Path) -> list[str]:
    text = exported.read_text(encoding="utf-8")
    m = re.search(r"def rationalVertices : VertexIndex → Fin 3 → ℚ := !\[\n(.*?)\n\]", text, re.S)
    if not m:
        raise SystemExit(f"{exported}: no rationalVertices definition found")
    rows = [line.strip().rstrip(",") for line in m.group(1).splitlines() if line.strip()]
    if len(rows) != 20 or not all(r.startswith("![") and r.endswith("]") for r in rows):
        raise SystemExit(f"{exported}: expected 20 rows, got {len(rows)}")
    return rows


def replace_def(text: str, header: str, rows: list[str]) -> str:
    pattern = re.compile(re.escape(header) + r"\n.*?\n\]", re.S)
    body = header + "\n" + ",\n".join("  " + r for r in rows) + "\n]"
    new, n = pattern.subn(lambda _: body, text, count=1)
    if n != 1:
        raise SystemExit(f"could not find `{header}` in Vertices.lean")
    return new


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--exported", type=Path,
                        default=REPO.parent / "nopert229" / "vertices229_exact27.lean")
    parser.add_argument("--vertices", type=Path,
                        default=REPO / "Noperthedron" / "Nopert229" / "Vertices.lean")
    args = parser.parse_args()
    rows = read_rows(args.exported)
    text = args.vertices.read_text(encoding="utf-8")
    text = replace_def(text, "def rationalVertices : VertexIndex → Fin 3 → ℚ := ![", rows)
    text = replace_def(text, "def seedVertex : SeedIndex → Fin 3 → ℚ := ![", rows[:4])
    args.vertices.write_text(text, encoding="utf-8")
    print(f"updated {args.vertices} from {args.exported}")


if __name__ == "__main__":
    main()
