#!/usr/bin/env python3
"""Install new exact rational vertices into Noperthedron/Nopert231/Vertices.lean.

Reads the rational vertex list exported by nopert229/codebdd231.cc
(vertices231_exact27.lean, by default next to this repository) and rewrites
the bodies of `rationalVertices` (all N = 5 S rows) and `seedVertex` (the
first S rows, i.e. orbit 0) in Vertices.lean, and the index sizes
(VertexIndex = Fin N, SeedIndex = Fin S). Vertex order is rotation-major
(index = S * orbit + seed), as generated by codebdd231.

After this, regenerate the tangent cones with
  python3 scripts/nopert231_emit_tangent_cones.py Noperthedron/Nopert231/GeneratedTangentCones.lean
and rebuild.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent


def read_rows(exported: Path) -> list[str]:
    text = exported.read_text(encoding="utf-8")
    m = re.search(r"def rationalVertices : VertexIndex → Fin 3 → ℚ := !\[\n(.*?)\n\]", text, re.S)
    if not m:
        raise SystemExit(f"{exported}: no rationalVertices definition found")
    rows = [line.strip().rstrip(",") for line in m.group(1).splitlines() if line.strip()]
    if len(rows) % 5 != 0 or not all(r.startswith("![") and r.endswith("]") for r in rows):
        raise SystemExit(f"{exported}: expected 5 * seeds rows, got {len(rows)}")
    return rows


def replace_def(text: str, header: str, rows: list[str]) -> str:
    pattern = re.compile(re.escape(header) + r"\n.*?\n\]", re.S)
    body = header + "\n" + ",\n".join("  " + r for r in rows) + "\n]"
    new, n = pattern.subn(lambda _: body, text, count=1)
    if n != 1:
        raise SystemExit(f"could not find `{header}` in Vertices.lean")
    return new


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--exported", type=Path,
                        default=REPO.parent / "nopert229" / "vertices231_exact27.lean")
    parser.add_argument("--vertices", type=Path,
                        default=REPO / "Noperthedron" / "Nopert231" / "Vertices.lean")
    args = parser.parse_args()
    rows = read_rows(args.exported)
    text = args.vertices.read_text(encoding="utf-8")
    n, seeds = len(rows), len(rows) // 5
    text = replace_def(text, "def rationalVertices : VertexIndex → Fin 3 → ℚ := ![", rows)
    text = replace_def(text, "def seedVertex : SeedIndex → Fin 3 → ℚ := ![", rows[:seeds])
    # Index sizes: VertexIndex = Fin n, SeedIndex = Fin seeds, index = seeds * k + s.
    for pattern, repl in [(r"abbrev VertexIndex := Fin \d+", f"abbrev VertexIndex := Fin {n}"),
                          (r"abbrev SeedIndex := Fin \d+", f"abbrev SeedIndex := Fin {seeds}"),
                          (r"⟨i\.val / \d+, by omega⟩", f"⟨i.val / {seeds}, by omega⟩"),
                          (r"⟨i\.val % \d+, Nat\.mod_lt", f"⟨i.val % {seeds}, Nat.mod_lt"),
                          (r"invFun ks := ⟨\d+ \* ks\.1\.val", f"invFun ks := ⟨{seeds} * ks.1.val")]:
        text, k = re.subn(pattern, repl, text)
        if k != 1:
            raise SystemExit(f"Vertices.lean: expected one match for {pattern}, got {k}")
    args.vertices.write_text(text, encoding="utf-8")
    print(f"updated {args.vertices} from {args.exported}")


if __name__ == "__main__":
    main()
