module

public import Noperthedron.RationalApprox.TrigLemmas
public import Noperthedron.Vertices.Taylor
public import Mathlib.Analysis.Real.Pi.Bounds

@[expose] public section

/-!
# Exact and rational vertices of Nopert #229

Candidate Nopert #229 is derived directly from the repair214 root construction (Compound M9b),
tweaking ring 1 by an azimuth rotation of -1.5e-3 rad, ring 2 radius by +1.5e-3,
top cap z by -1.5e-3, and deriving the z-coordinate of ring 1 algebraically to enforce exact coplanarity.

The vertices are scaled so that all vertices lie inside the unit sphere,
satisfying the GoodPoly invariant. The twenty vertices are generated by
rotating four seed vertices around the z-axis in increments of 2π/5.

TODO: If coordinates are ever regenerated, we should:
1. Use exact double coordinates of the 4 root vertices as the source of truth
   (bypassing the ASCII STL export).
2. Quantize to power-of-two denominators (p / 2^50) for zero-ULP conversion with Float
   and ~1.6x faster Stein binary GCD in GMP / Lean.
3. Planarize the 5 quad faces algebraically in ℚ (adjusting level-1 vertices by < 1e-15)
   so the rational convex hull has exactly 27 faces instead of 32.
See `noteperts/QUAD_FACES.md`.
-/

namespace Noperthedron.Nopert229

abbrev VertexIndex := Fin 20
abbrev SeedIndex := Fin 4
abbrev OrbitIndex := Fin 5

def rationalVertices : VertexIndex → Fin 3 → ℚ := ![
  ![17136292830659/400000000000000, 5680663556187131/10000000000000000, 5648167326177671/10000000000000000],
  ![-42773513204957/250000000000000, 9384169756351713/10000000000000000, 4802676718449/16000000000000],
  ![-2791996671138589/10000000000000000, 8916783831939151/10000000000000000, -420605170858861/10000000000000000],
  ![581211699562287/10000000000000000, 602579091333187/1000000000000000, -382169975802723/500000000000000],
  ![-5270246949360691/10000000000000000, 2162861152231751/10000000000000000, 5648167326177671/10000000000000000],
  ![-4726792748188159/5000000000000000, 1272666794475643/10000000000000000, 4802676718449/16000000000000],
  ![-1868627957476221/2000000000000000, 12511388959529/1250000000000000, -420605170858861/10000000000000000],
  ![-2775631710731053/5000000000000000, 1207418485492689/5000000000000000, -382169975802723/500000000000000],
  ![-921399766144207/2500000000000000, -1085985462790287/2500000000000000, 5648167326177671/10000000000000000],
  ![-4131696624115331/10000000000000000, -2149404605253097/2500000000000000, 4802676718449/16000000000000],
  ![-7455953197761/25000000000000, -8854924122951479/10000000000000000, -420605170858861/10000000000000000],
  ![-4012081174529903/10000000000000000, -2266669793986531/5000000000000000, -382169975802723/500000000000000],
  ![46756585289803/156250000000000, -4847564861402479/10000000000000000, 5648167326177671/10000000000000000],
  ![1380011310293969/2000000000000000, -411642950060219/625000000000000, 4802676718449/16000000000000],
  ![3749963394741599/5000000000000000, -5572735187461599/10000000000000000, -420605170858861/10000000000000000],
  ![767915222494757/2500000000000000, -10188661950973/19531250000000, -382169975802723/500000000000000],
  ![5535017234623651/10000000000000000, 673991002072371/5000000000000000, 5648167326177671/10000000000000000],
  ![1679233219444017/2000000000000000, 2263534535574267/5000000000000000, 4802676718449/16000000000000],
  ![1523518189628179/2000000000000000, 2705392183398847/5000000000000000, -420605170858861/10000000000000000],
  ![5910472006450693/10000000000000000, 327326655638497/2500000000000000, -382169975802723/500000000000000]
]

abbrev stlVertices := rationalVertices

def rationalVertex (i : VertexIndex) : Fin 3 → ℚ := rationalVertices i

def seedVertex : SeedIndex → Fin 3 → ℚ := ![
  ![17136292830659/400000000000000, 5680663556187131/10000000000000000, 5648167326177671/10000000000000000],
  ![-42773513204957/250000000000000, 9384169756351713/10000000000000000, 4802676718449/16000000000000],
  ![-2791996671138589/10000000000000000, 8916783831939151/10000000000000000, -420605170858861/10000000000000000],
  ![581211699562287/10000000000000000, 602579091333187/1000000000000000, -382169975802723/500000000000000]
]

def orbitIndex (i : VertexIndex) : OrbitIndex :=
  ⟨i.val / 4, by omega⟩

def seedIndex (i : VertexIndex) : SeedIndex :=
  ⟨i.val % 4, Nat.mod_lt _ (by omega)⟩

/-- The vertex ordering is rotation-major: four seeds for each of five orbits. -/
def indexEquiv : VertexIndex ≃ OrbitIndex × SeedIndex where
  toFun i := (orbitIndex i, seedIndex i)
  invFun ks := ⟨4 * ks.1.val + ks.2.val, by omega⟩
  left_inv i := by
    apply Fin.ext
    simp [orbitIndex, seedIndex]
    omega
  right_inv ks := by
    rcases ks with ⟨k, s⟩
    apply Prod.ext <;> apply Fin.ext <;> simp [orbitIndex, seedIndex] <;> omega

def vertexIndex (k : OrbitIndex) (s : SeedIndex) : VertexIndex :=
  indexEquiv.symm (k, s)

@[simp] theorem orbitIndex_vertexIndex (k : OrbitIndex) (s : SeedIndex) :
    orbitIndex (vertexIndex k s) = k := by
  exact congrArg Prod.fst (indexEquiv.apply_symm_apply (k, s))

@[simp] theorem seedIndex_vertexIndex (k : OrbitIndex) (s : SeedIndex) :
    seedIndex (vertexIndex k s) = s := by
  exact congrArg Prod.snd (indexEquiv.apply_symm_apply (k, s))

/-- A rational trigonometric approximation to the intended exact orbit vertex.
Angles in the second half of the orbit are reduced modulo `2π`, keeping their
absolute values below `π`. -/
def taylorVertex (i : VertexIndex) : Fin 3 → ℚ :=
  let k := orbitIndex i
  let k' : ℚ := if k.val ≤ 2 then k.val else k.val - 5
  let θ : ℚ := 2 * Noperthedron.piQ * k' / 5
  let c := RationalApprox.cosℚ θ
  let s := RationalApprox.sinℚ θ
  let v := seedVertex (seedIndex i)
  ![c * v 0 - s * v 1, s * v 0 + c * v 1, v 2]

def rationalPolyhedron : Polyhedron VertexIndex (Fin 3 → ℚ) :=
  ⟨rationalVertex⟩

noncomputable def exactVertex (i : VertexIndex) : ℝ³ :=
  RzL (2 * Real.pi * (orbitIndex i : ℝ) / 5) (toR3 (seedVertex (seedIndex i)))

noncomputable def exactPolyhedron : Polyhedron VertexIndex ℝ³ :=
  ⟨exactVertex⟩

noncomputable def exactVerts : Finset ℝ³ :=
  Finset.image exactVertex Finset.univ

theorem exactPolyhedron_hull :
    exactPolyhedron.hull = convexHull ℝ exactVerts := by
  simp only [Polyhedron.hull, exactPolyhedron, exactVerts, Finset.coe_image,
    Finset.coe_univ, Set.image_univ]
  congr 1

@[simp] theorem exactPolyhedron_vertex (i : VertexIndex) :
    exactPolyhedron.v i = exactVertex i := rfl

theorem exactVertex_norm_pos (i : VertexIndex) : 0 < ‖exactVertex i‖ := by
  rw [exactVertex, Bounding.Rz_preserves_norm, norm_pos_iff]
  intro h
  have hcoord := congrFun (congrArg WithLp.ofLp h) (2 : Fin 3)
  fin_cases i <;>
    simp [seedIndex, seedVertex, toR3] at hcoord <;>
    norm_num at hcoord

theorem exactVertex_norm_le_one (i : VertexIndex) : ‖exactVertex i‖ ≤ 1 := by
  rw [exactVertex, Bounding.Rz_preserves_norm]
  rw [← sq_le_sq₀ (norm_nonneg _) (by norm_num : (0 : ℝ) ≤ 1)]
  simp only [PiLp.norm_sq_eq_of_L2, Fin.sum_univ_three,
    Real.norm_eq_abs, sq_abs, one_pow]
  fin_cases i <;>
    simp [seedIndex, seedVertex, toR3] <;>
    norm_num

noncomputable def exactGoodPoly : GoodPoly VertexIndex where
  vertices := exactPolyhedron
  nontriv := exactVertex_norm_pos
  vertex_radius_le_one := exactVertex_norm_le_one

end Noperthedron.Nopert229

end
